# iOS CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/ios-migrating-from-1-2/ for more details
#
version: 2
jobs:
  run_danger:
    macos:
      xcode: "11.0"
    steps:
      - checkout
      - run:
          command: bundle install
      - run: 
          command: bundle exec danger --verbose
  test:
    # Specify the Xcode version to use
    macos:
      xcode: "11.0"

    steps:
      - checkout
      - run:
          name: Build and run tests
          command: fastlane scan
          environment:
            SCAN_DEVICE: iPhone X
            SCAN_SCHEME: WeatherApp

  lint:
    macos:
      xcode: "11.0"
    steps:
      - run:
          name: install swift lint
          command: brew install swiftlint
      - checkout
      - run:
          name: run swift lint
          command: fastlane run swiftlint

workflows:
  version: 2
  checkout_test:
    jobs:
      - run_danger